name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST \
            https://api.vercel.com/v1/integrations/deploy/prj_lmTrn9GLUgoNY4efKoOJaeP13U5N/cKxQDHuVBW \
            -H "Content-Type: application/json"
